# Generated by Django 5.1 on 2024-10-02 09:22

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Astrax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50, unique=True)),
                ('image', models.ImageField(default='default.jpg', upload_to='images/Astrax')),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pleiades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50, unique=True)),
                ('image', models.ImageField(default='default.jpg', upload_to='images/Pleiades')),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('problem_statement', models.URLField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='Utkarsh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50, unique=True)),
                ('image', models.ImageField(default='default.jpg', upload_to='images/Utkarsh')),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('problem_statement', models.URLField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='Zenith',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50, unique=True)),
                ('image', models.ImageField(default='default.jpg', upload_to='images/Zenith')),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('problem_statement', models.URLField(blank=True, default='')),
            ],
        ),
    ]
