# Generated by Django 5.1 on 2024-10-02 12:28

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50, unique=True)),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('insta', models.URLField(blank=True, default='#/')),
                ('linkedin', models.URLField(blank=True, default='#/')),
                ('image', models.ImageField(default='default.jpg', upload_to='Alumni')),
            ],
        ),
    ]
