# Generated by Django 5.1 on 2024-10-02 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MemberDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('message', models.CharField(max_length=100)),
                ('position', models.CharField(choices=[('A', 'Coordinator'), ('B', 'Co-coordinator'), ('C', 'Core Team'), ('D', 'Mentor')], default='C', max_length=1)),
                ('linkedin_url', models.CharField(max_length=100)),
                ('instagram_url', models.CharField(max_length=100)),
                ('image', models.ImageField(default='default.webp', upload_to='images/CoreTeam')),
            ],
        ),
    ]
