# Generated by Django 3.1.2 on 2020-12-31 20:21

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='club_activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(max_length=50, unique=True)),
                ('content', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('image', models.ImageField(default='default.jpg', upload_to='Homepage/club_activity')),
            ],
        ),
        migrations.CreateModel(
            name='coordinators',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('fb', models.CharField(default='#', max_length=50)),
                ('insta', models.CharField(default='#', max_length=50)),
                ('git', models.CharField(default='#', max_length=50)),
                ('linkedin', models.CharField(default='#', max_length=50)),
                ('batch', models.IntegerField(default=2023)),
                ('image', models.ImageField(default='default.jpg', upload_to='team/coordinators')),
            ],
        ),
        migrations.CreateModel(
            name='core_team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('fb', models.CharField(default='#', max_length=50)),
                ('insta', models.CharField(default='#', max_length=50)),
                ('git', models.CharField(default='#', max_length=50)),
                ('linkedin', models.CharField(default='#', max_length=50)),
                ('batch', models.IntegerField(default=2023)),
                ('image', models.ImageField(default='default.jpg', upload_to='team/core_team')),
            ],
        ),
        migrations.CreateModel(
            name='homepage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=50, unique=True)),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('image', models.ImageField(default='default.jpg', upload_to='Homepage')),
            ],
        ),
        migrations.CreateModel(
            name='utkarshEvents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50, unique=True)),
                ('image', models.ImageField(default='default.jpg', upload_to='Utkarsh/event_image')),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('problem_statement', models.URLField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='zenithEvents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50, unique=True)),
                ('image', models.ImageField(default='default.jpg', upload_to='Zenith/event_image')),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('problem_statement', models.URLField(blank=True, default='')),
            ],
        ),
    ]
