# Generated by Django 3.1.2 on 2020-12-16 17:43

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stac_iitmandi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='club_activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(max_length=50, unique=True)),
                ('content', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('image', models.ImageField(default='default.jpg', upload_to='club_activity')),
            ],
        ),
    ]
