# Generated by Django 3.1.2 on 2021-01-01 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stac_iitmandi', '0002_auto_20201231_2028'),
    ]

    operations = [
        migrations.CreateModel(
            name='achievements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achievement', models.CharField(max_length=150, unique=True)),
                ('link', models.CharField(default='#', max_length=150)),
            ],
        ),
        migrations.AlterField(
            model_name='coordinators',
            name='fb',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='coordinators',
            name='git',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='coordinators',
            name='insta',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='coordinators',
            name='linkedin',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='core_team',
            name='fb',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='core_team',
            name='git',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='core_team',
            name='insta',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='core_team',
            name='linkedin',
            field=models.URLField(blank=True, default=''),
        ),
    ]
