# Generated by Django 3.1.2 on 2020-12-20 19:33

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stac_iitmandi', '0002_club_activity'),
    ]

    operations = [
        migrations.CreateModel(
            name='homepage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=50, unique=True)),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('image', models.ImageField(default='default.jpg', upload_to='Homepage')),
            ],
        ),
        migrations.AlterField(
            model_name='club_activity',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='Homepage/club_activity'),
        ),
    ]
