# Generated by Django 3.1.2 on 2020-12-29 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stac_iitmandi', '0002_remove_zenithevents_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='zenithevents',
            name='name',
            field=models.CharField(default='', max_length=50, unique=True),
        ),
    ]
