# Generated by Django 3.1.2 on 2020-12-29 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stac_iitmandi', '0003_zenithevents_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zenithevents',
            name='problem_statement',
            field=models.URLField(blank=True, null=True),
        ),
    ]
