# Generated by Django 3.1.2 on 2021-01-02 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stac_iitmandi', '0003_auto_20210101_1554'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videogallery',
            name='image',
        ),
        migrations.RemoveField(
            model_name='videogallery',
            name='name',
        ),
    ]
