# Generated by Django 3.1.2 on 2021-01-02 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stac_iitmandi', '0005_videogallery_videoname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Links',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linkname', models.CharField(max_length=50, unique=True)),
                ('link', models.CharField(default='#/', max_length=150)),
            ],
        ),
    ]
