# Generated by Django 3.1.2 on 2020-12-29 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stac_iitmandi', '0005_auto_20201229_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zenithevents',
            name='problem_statement',
            field=models.URLField(blank=True, default='/#'),
        ),
    ]
