# Generated by Django 3.1.2 on 2020-12-30 07:42

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stac_iitmandi', '0007_auto_20201229_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zenithevents',
            name='problem_statement',
            field=ckeditor.fields.RichTextField(blank=True, default='', null=True),
        ),
    ]
