# Generated by Django 3.1.2 on 2020-12-30 07:50

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stac_iitmandi', '0008_auto_20201230_0742'),
    ]

    operations = [
        migrations.CreateModel(
            name='utkarshEvents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50, unique=True)),
                ('image', models.ImageField(default='default.jpg', upload_to='Utkarsh/event_image')),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('problem_statement', ckeditor.fields.RichTextField(blank=True, default='', null=True)),
            ],
        ),
    ]
