# Generated by Django 3.1.2 on 2020-12-30 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stac_iitmandi', '0011_auto_20201230_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utkarshevents',
            name='problem_statement',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='zenithevents',
            name='problem_statement',
            field=models.URLField(blank=True, default=''),
        ),
    ]
