# Generated by Django 5.1 on 2024-10-03 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fests',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='Homepage/Fests'),
        ),
    ]
